version: '3.9'
services:
  evoting-api-spring:
    container_name: spring-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://evoting_database:3306/db_evoting?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: crymuzz
      DB_PASSWORD: 1234
      JWT_SECRET: cff10b0258a363c968d76a7eda9e15a2c2052755d1d3b2cb7edf0d74a86bcc3077bdb71201c77e34a79d6acdf2bc89527b415e4a246edaea50263d0b6ed2c272
      JWT_VALIDITY_SECONDS: 2592000
    restart: always
    depends_on:
      evoting_database:
        condition: service_healthy

  evoting_database:
    image: mysql:8.3.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_evoting
      MYSQL_USER: crymuzz
      MYSQL_PASSWORD: 1234
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10