version: "3.9"
services:
  spring-api-image:
    image: spring-api-image
    container_name: spring-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: mysql_evoting
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: test_blockchain
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql
networks:
  spring-network:
volumes:
  mysql-volume:
